// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhtyhbjbebwuzciencrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJodHloYmpiZWJ3dXpjaWVuY3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjgyMDUsImV4cCI6MjA3MDYwNDIwNX0.m0yMRx6yeLl8vmLOr1981GAXkAB5csnFhy5dMHIVnxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});